receivers:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

      http:
        endpoint: 0.0.0.0:4318


processors:

  batch:
    timeout: 5s
    send_batch_size: 1024

  attributes:
    actions:
      - key: service.name
        action: upsert


exporters:

  debug:
    verbosity: detailed

  elasticsearch:
    endpoints:
      - http://elasticsearch:9200

    logs_index: otel-logs
    traces_index: otel-traces
    metrics_index: otel-metrics


service:

  pipelines:

    logs:
      receivers:
        - otlp
      processors:
        - batch
        - attributes
      exporters:
        - debug
        - elasticsearch

    traces:
      receivers:
        - otlp
      processors:
        - batch
        - attributes
      exporters:
        - debug
        - elasticsearch

    metrics:
      receivers:
        - otlp
      processors:
        - batch
        - attributes
      exporters:
        - debug
        - elasticsearch
